version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: java-postgres
    environment:
      POSTGRES_DB: LAB2_karelin_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  webserv:
    build: ./
    container_name: webservice
    ports:
      - 9991:9991

  sushi:
    build: https://github.com/kkarelinn/Lab2SushiShop.git
    container_name: sushi
    ports:
      - 9999:9999
    depends_on:
      - postgres
      - webserv

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/LAB2_karelin_base
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      currency_USDurl: http://host.docker.internal:9991/currency?code=USD